/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mainpackage;

import java.awt.AWTException;
import java.awt.Dimension;
import java.awt.Robot;
import java.awt.Toolkit;
import static java.awt.event.InputEvent.BUTTON1_MASK;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.JOptionPane;

/**
 *
 * @author Adam Jensen
 */
public class Visuma extends javax.swing.JFrame {

    int j = 1;
    private Robot rt;
    int[] ft = new int[12];
//    Dimension sSize = Toolkit.getDefaultToolkit().getScreenSize();
//    int ver = sSize.height;
//    int hor = sSize.width;       
//    int X = ver / 2;
//    int Y = hor / 2;
    
    
    Dimension btnSize2 = new Dimension(50,50);
    Dimension btnSize3 = new Dimension(50,50);
     
    /**
     * Creates new form Visuma
     */
    public Visuma() {
        initComponents();
//        str.setLocation(X, Y);
        
        try(BufferedReader br = new BufferedReader(new FileReader("C:\\Users\\subqwerty\\Desktop\\урок.txt")))
        {
            String s;
            int i = 0;
            while((s=br.readLine())!=null){
                ft[i] = Integer.valueOf(s);
                //System.out.println(ft[i]);
                i++;
            }
        }
         catch(IOException ex){
            System.out.println(ex.getMessage());
        }
        btn.setLocation(ft[0], ft[1]);
        //btn.setVisible(false);
       
        
        
        
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn = new javax.swing.JButton();
        str = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setExtendedState(MAXIMIZED_BOTH);
        setUndecorated(true);
        setOpacity(0.5F);

        btn.setBackground(new java.awt.Color(204, 0, 51));
        btn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn.setMaximumSize(new java.awt.Dimension(100000, 10000));
        btn.setMinimumSize(new java.awt.Dimension(0, 0));
        btn.setPreferredSize(new java.awt.Dimension(100, 100));
        btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActionPerformed(evt);
            }
        });

        str.setBackground(new java.awt.Color(0, 0, 255));
        str.setText("Начать урок");
        str.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                strActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 721, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(str)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(150, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(str)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActionPerformed
        try {
            rt = new Robot();
        } 
        catch (AWTException ex) {}
        
        if(j==1){
            this.setVisible(false);
           rt.mousePress(BUTTON1_MASK);
           rt.mouseRelease(BUTTON1_MASK);
           this.setVisible(true);
           btn.setLocation(ft[4], ft[5]);
        }
        if(j==2){
           this.setVisible(false);
           rt.mousePress(BUTTON1_MASK);
           rt.mouseRelease(BUTTON1_MASK);
           this.setVisible(true);
           btn.setLocation(ft[9], ft[10]);
        }
        if(j==3){
            this.setVisible(false);
            rt.mousePress(BUTTON1_MASK);
            rt.mouseRelease(BUTTON1_MASK);
            this.setVisible(true);
            System.exit(0);
        }
        
        j++;
    }//GEN-LAST:event_btnActionPerformed

    
    int a=ft[2]-ft[0];
    int b=ft[3]-ft[1];
    Dimension btnSize1 = new Dimension(ft[0],ft[1]);
    
    private void strActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_strActionPerformed
         System.out.println(a);
        System.out.println(b);
        System.out.println(ft[1]);
        System.out.println(ft[0]);
        
        
       
//        JOptionPane.showMessageDialog(this, "Вы запустили урок \"Word\"",
//                  "Начало", JOptionPane.WARNING_MESSAGE);
       // btn.setVisible(true);
       
        btn.setSize(btnSize1);
        btn.setLocation(ft[0], ft[1]);
        
        //str.setVisible(false);
        btn.setText("1");
        
    }//GEN-LAST:event_strActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Visuma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Visuma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Visuma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Visuma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Visuma().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn;
    private javax.swing.JButton str;
    // End of variables declaration//GEN-END:variables
}
