/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mainpackage;

import java.awt.AWTException;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Robot;
import java.awt.Toolkit;
import static java.awt.event.InputEvent.BUTTON1_MASK;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.JOptionPane;

/**
 *
 * @author Adam Jensen
 */
public class Visuma extends javax.swing.JFrame {

    int j = 0;
    private Robot rt;
    String LesName;
    int[] ln = new int[12];
    Dimension sSize = Toolkit.getDefaultToolkit().getScreenSize();
    int ver = sSize.height;
    int hor = sSize.width;
    String SIZE = Integer.toString(hor)+"x"+Integer.toString(ver);
//    int X = ver / 2;
//    int Y = hor / 2;
    
    
    //Dimension btnSize2 = new Dimension(50,50);
    //Dimension btnSize3 = new Dimension(50,50);
    
    /**
     * Creates new form Visuma
     */
    public Visuma() {
        initComponents();
//        str.setLocation(X, Y);
        
        try(BufferedReader br = new BufferedReader(new FileReader("C:\\Visuma\\урок.txt")))
        {
            System.out.println(SIZE);
            LesName = br.readLine();
            String s;
            if(SIZE.equals(br.readLine())){    
            JOptionPane.showMessageDialog(this, "Проверка на разрешение пройдена",
                        "Урок совместим", JOptionPane.WARNING_MESSAGE);
            }
            else{ JOptionPane.showMessageDialog(this, "Разрешение экрана не соотвецтвует заданому в уроке",
                        "Не совместимость", JOptionPane.WARNING_MESSAGE);
                System.exit(0);
            }
            int i = 0;
            while((s=br.readLine())!=null){
                ln[i] = Integer.valueOf(s);
                System.out.println(ln[i]);
                i++;
            }
        }
         catch(IOException ex){
            System.out.println(ex.getMessage());
        }
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setExtendedState(MAXIMIZED_BOTH);
        setUndecorated(true);
        setOpacity(0.5F);

        btn.setBackground(new java.awt.Color(51, 51, 255));
        btn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn.setToolTipText("");
        btn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn.setMaximumSize(new java.awt.Dimension(100000, 10000));
        btn.setMinimumSize(new java.awt.Dimension(0, 0));
        btn.setPreferredSize(new java.awt.Dimension(100, 100));
        btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 821, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 296, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActionPerformed
        try {
            rt = new Robot();
        } 
        catch (AWTException ex) {}
        
        if(j==0){
            System.out.println("Кнопка Старт");
            JOptionPane.showMessageDialog(this, "Вы запустили урок \""+LesName+"\"",
            "Начало", JOptionPane.WARNING_MESSAGE);
            btn.setSize(ln[6]-ln[4], ln[7]-ln[5]);
            btn.setLocation(ln[4], ln[5]);
            btn.setBackground(Color.red);
        }
        if(j==1){
            System.out.println("Кнопка 1");
            this.setVisible(false);
            rt.mousePress(BUTTON1_MASK);
            rt.mouseRelease(BUTTON1_MASK);
            this.setVisible(true);
            btn.setSize(ln[6]-ln[4], ln[7]-ln[5]);
            btn.setLocation(ln[4], ln[5]);
        }
        if(j==2){
            System.out.println("Кнопка 2");
            this.setVisible(false);
            rt.mousePress(BUTTON1_MASK);
            rt.mouseRelease(BUTTON1_MASK);
            this.setVisible(true);
            btn.setSize(ln[10]-ln[8], ln[11]-ln[9]);
            btn.setLocation(ln[8], ln[9]);
        }
        if(j==3){
            System.out.println("Кнопка 3 (последняя)");
            this.setVisible(false);
            rt.mousePress(BUTTON1_MASK);
            rt.mouseRelease(BUTTON1_MASK);
            this.setVisible(true);
            System.exit(0);
        }
        
        j++;
    }//GEN-LAST:event_btnActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Visuma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Visuma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Visuma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Visuma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Visuma().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn;
    // End of variables declaration//GEN-END:variables
}
